---
title: "recipes-epi"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(jsonlite)
library(tm)
library(klaR)
setwd("~/recipes-epi")

recipes <-fromJSON("full_format_recipes.json")

ingredcorpus <- paste(recipes$ingredients)
ingredcorpus <- gsub("[^A-Za-z]"," ",ingredcorpus)
allingredtf <- termFreq(ingredcorpus)
allingred <- data.frame(allingredtf)
allingred$name <- rownames(allingred)

allingred <- allingred[order(allingred$allingredtf),]
allingredc <- allingred
allingredc$name <- gsub("es$|s$","",allingred$name)


allingredc <- aggregate(allingredc$allingredtf, by=list(Category=allingredc$name), FUN=sum)

allingredc <- allingredc[order(allingredc$x, decreasing = TRUE),]


write.csv(allingredc, file="allingredc.csv")

allingredclean <- read.csv("allingredcclean.csv")
allingredclean <- subset(allingredclean, allingredclean$Category != "")
allingredclean <- aggregate(allingredclean$x, by=list(Category=allingredclean$Category), FUN=sum)

allingredclean <- allingredclean[order(allingredclean$x, decreasing = TRUE),]
topingred <- subset(allingredclean, allingredclean$x > 100)

topingred$plural <- paste(topingred$Category, "s", sep="")
write.csv(topingred, file="topingred.csv")

topingred <- topingred[,2:4]
colnames(topingred) <- c("name", "count", "plural")

lstringin <- function(x, y ){
  grepl(x, y, fixed= TRUE)
}
````



```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

singin <- lapply(topingred$name, function(x) grepl(x, recipes$ingredients, fixed=TRUE))
plurin <- lapply(topingred$plural, function(x) grepl(x, recipes$ingredients, fixed=TRUE))
testsi <- singin[1:10]
singindf <- t(as.data.frame(singin))


rownames(singindf) <-topingred$name
colnames(singindf) <- recipes$title
plurindf <- t(as.data.frame(plurin))

ingredindf <- (singindf + 0) + (plurindf + 0)
ingredindf <- (ingredindf > 0) + 0

#we will run kmoeds for a range of different number of centres, using a toy dataset, with just 1000 recipes

simp <- t(ingredindf[,1:1000])
wdiff <- 0

# For 1 to 15 cluster centers
for (i in 1:10 ){
  km.out <- kmodes(simp, modes = i)
  # Save total within sum of squares to wss variable
  wdiff[i] <- km.out$withindiff
}


````









```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}


````